joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 1.31
    has_acceleration_limits: false
    max_acceleration: 0
  joint_0:
    has_velocity_limits: true
    max_velocity: 1.31
    has_acceleration_limits: false
    max_acceleration: 0
  joint_2:
    has_velocity_limits: true
    max_velocity: 1.57
    has_acceleration_limits: false
    max_acceleration: 0
  joint_3:
    has_velocity_limits: true
    max_velocity: 1.57
    has_acceleration_limits: false
    max_acceleration: 0
  joint_5:
    has_velocity_limits: true
    max_velocity: 2.36
    has_acceleration_limits: false
    max_acceleration: 0
  joint_6:
    has_velocity_limits: true
    max_velocity: 2.36
    has_acceleration_limits: false
    max_acceleration: 0
  joint_4:
    has_velocity_limits: true
    max_velocity: 2.51
    has_acceleration_limits: false
    max_acceleration: 0