controller_list:
  - name: fake_lower_body_controller
    joints:
      - base_prismatic_joint_x
      - base_prismatic_joint_y
      - base_rotate_joint
      - pelvis1_z_joint
      - pelvis1_y_joint
      - pelvis1_x_joint
      - upper_left_leg_z_joint
      - upper_left_leg_y_joint
      - upper_left_leg_x_joint
      - lower_left_leg_joint
      - left_foot_z_joint
      - left_foot_y_joint
      - left_foot_x_joint
      - left_foot2_z_joint
      - left_foot2_y_joint
      - left_foot2_x_joint
      - upper_right_leg_z_joint
      - upper_right_leg_y_joint
      - upper_right_leg_x_joint
      - lower_right_leg_joint
      - right_foot_z_joint
      - right_foot_y_joint
      - right_foot_x_joint
      - right_foot2_z_joint
      - right_foot2_y_joint
      - right_foot2_x_joint